services:
  redis:
    image: redis:latest
    ports:
      - 6379:6379
    volumes:
      - redis-data:/data
      - redis-data:/usr/local/conf/redis.conf
    labels:
      - 'name=redis'
      - 'mode=standalone'
    restart: always
    command: redis-server /usr/local/conf/redis.conf
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 10s
      timeout: 5s
      retries: 3
  api-server:
    image: api-server:latest

volumes:
  redis-data: